name: pornhub自动爬取

on:
  schedule:
    # 定时任务，每天凌晨 1 点运行一次
    - cron: '0 1 * * *'

  workflow_dispatch: # 允许手动触发工作流

jobs:
  crawl:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 使用 Python 3.10 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # 更新 pip
        pip install -r requirements.txt  # 安装项目依赖

    - name: Run main
      run: |
        python main.py  # 根据项目结构，运行相应的爬虫脚本
      env:
        # 如果有敏感信息，例如 Cookies 或其他配置，可以使用 GitHub Secrets 存储
        COOKIES: ${{ secrets.PORNHUB_COOKIES }}
